# Generated by Django 4.2.4 on 2023-08-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trainer", "0003_alter_trainer_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
