# Generated by Django 4.2.4 on 2023-08-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_student_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile",
            field=models.ImageField(
                default="default.jpg", null=True, upload_to="profiles_student/"
            ),
        ),
    ]
