# Generated by Django 4.2.4 on 2023-08-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0004_alter_student_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile",
            field=models.ImageField(null=True, upload_to="profiles_student/"),
        ),
    ]
