# Generated by Django 4.2.4 on 2023-08-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0005_alter_student_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile",
            field=models.ImageField(
                blank=True,
                default="default.jpg",
                null=True,
                upload_to="profiles_student/",
            ),
        ),
    ]
