# Generated by Django 4.2.4 on 2023-08-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0006_alter_student_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles_student/"
            ),
        ),
    ]
